name: consultations_app_test
description: Interview Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  mocktail: ^0.3.0
  font_awesome_flutter: ^10.3.0
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

#  assets:
